import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/app/components/logo";
import Contact from "@/app/components/contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Soft&warm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen relative`}>

          <Logo />

          {children}

          <footer className="bg-gray-100 w-full mt-auto">
          <div className="container mx-auto px-4 py-8">
            <h1 className="text-2xl text-center font-bold mb-4">Contact Us</h1>
            <Contact />
          </div>
        </footer>

      </body>
    </html>
  );
}
