import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/app/components/logo" ;
import Contact from "@/app/components/contact" ;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Logo/>
        {children}
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-2xl text-center font-bold mb-4">Contact Us</h1>
          <Contact />
        </div>
      </body>
    </html>
  );
}
